steps:
  # Run tests
  - name: 'python:3.8'
    entrypoint: pip
    args: ['install', 'pytest', 'apache-airflow[google]==2.10.2', 'duckdb']

  - name: 'python:3.8'
    entrypoint: python
    args: ['-m', 'pytest', 'tests/']

  # Sync to Composer
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get Composer's GCS bucket
        COMPOSER_BUCKET=$$(gcloud composer environments describe ${_COMPOSER_ENV_NAME} \
          --location=${_COMPOSER_LOCATION} \
          --format="get(config.dagGcsPrefix)")
        
        # Sync DAGs and plugins
        gsutil -m rsync -r dags/ $$COMPOSER_BUCKET/dags
        gsutil -m rsync -r plugins/ $$COMPOSER_BUCKET/plugins

substitutions:
  _COMPOSER_ENV_NAME: airr-labs-interview   # Default value, override in trigger
  _COMPOSER_LOCATION: asia-southeast1        # Default value, override in trigger

options:
  logging: CLOUD_LOGGING_ONLY
