name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.AIRR_LABS_GCP_SA_KEY }}'
      
      - uses: actions/checkout@v2

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        if: steps.auth.outcome == 'success'

      - name: Deploy to Cloud Composer
        if: steps.auth.outcome == 'success'
        run: |
          # Get Composer's GCS bucket
          COMPOSER_BUCKET=$(gcloud composer environments describe ${{ secrets.AIRR_LABS_COMPOSER_ENV_NAME }} \
            --location=${{ secrets.AIRR_LABS_COMPOSER_LOCATION }} \
            --format="get(config.dagGcsPrefix)")
          
          # Sync DAGs
          gsutil -m rsync -r dags/ $COMPOSER_BUCKET/dags
          
          # Sync plugins
          gsutil -m rsync -r plugins/ $COMPOSER_BUCKET/plugins
          
          echo "Deployment completed successfully"
