name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: asia.gcr.io/personal-project-447516/airflow-github-etl:0.0.1
      credentials:
          username: _json_key
          password: ${{ secrets.AIRR_LABS_GCP_SA_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Run tests in container
        with:
          args: |
            /bin/bash -c "
            pylint dags plugins tests &&
            pytest -s dags/ plugins/ tests/ --cov=./ --cov-report=xml"
