name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: asia.gcr.io/${{ secrets.AIRR_LABS_GCP_PROJECT_ID }}/airflow-github-etl:0.0.1
    strategy:
      matrix:
        python-version: [3.11]  # Composer 3 uses Python 3.11

    steps:
    - uses: actions/checkout@v2

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov apache-airflow[google]==2.10.2 duckdb

    - name: Run linting
      run: |
        pylint dags plugins tests

    - name: Run tests
      run: |
        pytest tests/ --cov=./ --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
