name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: asia.gcr.io/personal-project-447516/airflow-github-etl:0.0.1
      credentials:
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
    steps:
    - uses: actions/checkout@v2

    - name: Run linting
      run: |
        pylint dags plugins tests

    - name: Run tests
      run: |
        pytest tests/ --cov=./ --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
